name: Testing github workflow

on:
  push:
    branches: ['master']

  workflow_dispatch:

jobs:
  testing_checkout:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4
        #run: git clone -b branchname github_url
      - name: run echo commands
        run: echo "Checkout is done successfully"
